### ISSUE TITLE
[Week 1] CPOutfitters Progress Update - Review My App

### ISSUE THREAD

**Issue by cthompson527** [cpoutfitters/cpoutfitters#12]
My app is complete after the first week of group assignment. Please review. /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.
- Good to see that you have already started adding UI polish to your app. :star2:
